name: CI Red3Conecta

on:
  push:
    branches: [ landing-page, staging, dev, main ]
  pull_request:
    branches: [ main, staging, dev, landing-page ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install
        run: npm install
        
      - name: Check Astro types
        run: npm run check
        
      - name: Build
        run: npm run build